PRIVACY_STATUS_PUBLIC = 'public'
PRIVACY_STATUS_PRIVATE = 'private'
PRIVACY_STATUS_UNLISTED = 'unlisted'


PRIVACY_STATUS = [
    (PRIVACY_STATUS_PUBLIC, PRIVACY_STATUS_PUBLIC),
    (PRIVACY_STATUS_PRIVATE, PRIVACY_STATUS_PRIVATE),
    (PRIVACY_STATUS_UNLISTED, PRIVACY_STATUS_UNLISTED)
]