# Generated by Django 3.1.7 on 2021-03-20 17:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(null=True)),
                ('category', models.IntegerField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('privacy_status', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('unlisted', 'unlisted')], default='private', max_length=20)),
                ('id_youtube', models.CharField(max_length=50, null=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('origin_channel', models.CharField(max_length=50)),
                ('origin_video_url', models.URLField(max_length=250)),
            ],
        ),
    ]
